db:
  synchronize: true
  host: 'dpg-ct10t80gph6c73beou10-a'
  database: 'iwms_db_3v9i'
  username: 'iwms_client_user'
  password: 'HlD2V8xehhAsgFtfNveIe2YuTsPTemlL'
jwt:
  secret: 'topSecretSecret001'