db:
  synchronize: true
  host: 'dpg-csj54368ii6s73cvh8og-a'
  database: 'iwms_db_ijww'
  username: 'iwms_client_user'
  password: 'afAUuu4qYvfLWkJUQeIcrR037cs2BPwD'
jwt:
  secret: 'topSecretSecret001'